version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    platform: linux/amd64
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    platform: linux/amd64
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

# Spark Master
  spark-master:
    image: apache/spark:3.5.0
    platform: linux/amd64
    container_name: spark-master
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - SPARK_NO_DAEMONIZE=true

  # Spark Worker
  spark-worker:
    image: apache/spark:3.5.0
    platform: linux/amd64
    container_name: spark-worker
    depends_on:
      - spark-master
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    environment:
      - SPARK_NO_DAEMONIZE=true

  mysql:
    image: mysql:8.0.36
    platform: linux/amd64
    container_name: payment-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 2334
      MYSQL_DATABASE: payment_db

  fraud-detector:
    build: "./fraud-detector 2"
    container_name: fraud-detector
    depends_on:
      - kafka
    ports:
      - "8000:8000"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  fraud-dashboard:
    build: "./fraud-dashboard 2"
    container_name: fraud-dashboard
    depends_on:
      - fraud-detector
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true

  payment-generator:
    build: ./payment-generator
    container_name: payment-generator
    depends_on:
      - kafka
    ports:
      - "8081:8080"
    environment:
      SPRING_KAFKA_PRODUCER_BOOTSTRAP_SERVERS: kafka:9092